openapi: 3.0.3
info:
  title: User Management Service
  description: Сервис предназначен для выполнения базовых операций над учетными записями пользователей
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

security:
  - bearerAuth: [ ]

tags:
  - name: employee-personal-data
    description: Персональные данные сотрудника

paths:
  /user-management/v1/employee/personal-data/card:
    post:
      tags:
        - employee-personal-data
      summary: UMS-0001. Создание персональных данных сотрудника
      description: Метод создает персональные данные сотрудника
      operationId: createEmployeePersonalData
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        description: Персональные данные сотрудника для создания
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeePersonalDataCardPostRequest'
      responses:
        '201':
          description: Успешное создание данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeePersonalDataCardPostResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Данные уже существуют
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - employee-personal-data
      summary: UMS-0002. Получение персональных данных сотрудника
      description: Метод возвращает персональные данные сотрудника
      operationId: getEmployeePersonalData
      security:
        - bearerAuth: [ ]
      parameters:
        - name: userGUID
          in: header
          required: true
          description: Глобальный идентификатор пользователя (далее будет изменен на JWT)
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Успешное получение данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeePersonalDataCardResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT токен для авторизации

  schemas:
    EmployeePersonalDataCardResponse:
      type: object
      required:
        - employeeUuid
      properties:
        employeeUuid:
          type: string
          description: Уникальный идентификатор пользователя в системе
        email:
          type: string
          description: Корпоративная почта
        globalState:
          $ref: '#/components/schemas/EmployeeGlobalState'
        generalInfo:
          $ref: '#/components/schemas/EmployeeGeneralInfo'
        createDatetime:
          type: string
          description: Дата создания записи
        updateDatetime:
          type: string
          description: Дата обновления записи

    EmployeePersonalDataCardPostRequest:
      type: object
      required:
        - corpEmail
      properties:
        generalInfo:
          $ref: '#/components/schemas/EmployeeGeneralInfo'
        corpEmail:
          type: string
          description: "Корпоративная почта"
        globalState:
          type: string
          description: "Системное имя статуса пользователя"


    EmployeePersonalDataCardPostResponse:
      type: object
      required:
        - employeeUuid
        - email
      properties:
        employeeUuid:
          type: string
          description: Уникальный идентификатор пользователя в системе
        email:
          type: string
          description: Корпоративная почта
        globalState:
          $ref: '#/components/schemas/EmployeeGlobalState'
        generalInfo:
          $ref: '#/components/schemas/EmployeeGeneralInfo'
        createDatetime:
          type: string
          description: Дата создания записи
        updateDatetime:
          type: string
          description: Дата обновления записи

    EmployeeGlobalState:
      type: object
      required:
        - sysName
        - name
      properties:
        sysName:
          type: string
          description: Системное имя статуса
          minLength: 1
          maxLength: 100
        name:
          type: string
          description: Наименование статуса
          maxLength: 100
          nullable: true
        description:
          type: string
          description: Описание статуса
          minLength: 1
          maxLength: 100
        imageUrl:
          type: string
          description: Ссылка на картинку статуса

    EmployeeGeneralInfo:
      type: object
      required:
        - personalData
      properties:
        personalData:
          $ref: '#/components/schemas/PersonalData'

    PersonalData:
      type: object
      required:
        - firstName
        - lastName
        - birthDate
      properties:
        firstName:
          type: string
          description: Имя пользователя
          minLength: 1
          maxLength: 100
        secondName:
          type: string
          description: Отчество пользователя
          maxLength: 100
          nullable: true
        lastName:
          type: string
          description: Фамилия пользователя
          minLength: 1
          maxLength: 100
        birthDate:
          type: string
          format: date
          description: Дата рождения в формате YYYY-MM-DD

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Код ошибки
        message:
          type: string
          description: Описание ошибки
        details:
          type: array
          description: Детали ошибки (опционально)
          items:
            type: string
        timestamp:
          type: string
          format: date-time
          description: Время возникновения ошибки
        path:
          type: string
          description: Путь запроса, вызвавшего ошибку
